name: Publish Manifests

on:
  push:
    # Build and publish artifacts for a release
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Publish Manifests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: RELEASE=${{ github.ref_name }} make manifests
    - name: ls
      run: ls 
    - name: ls dir
      run: ls ${{ github.ref_name }}/*.yaml
    - name: Upload Manifests to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.ref_name }}/*.yaml
        file_glob: true
        tag: ${{ github.ref_name }}
        overwrite: true
        release_name: Release ${{ github.ref_name }}
        body: "This is my release text"
